# Site settings
title: Jacob Jenkins
email: jacob@jacobejenkins.com
description: > # this means to ignore newlines until "baseurl:"
    It's going to be fine, calm down
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jacobejenkins.com" # the base hostname & protocol for your site
twitter_username: wipeyadocsoff
github_username:  jacobj

# Build settings
markdown: kramdown
