# Site settings
title: Jacob Jenkins
email: jacob@jacobejenkins.com
description: > # this means to ignore newlines until "baseurl:"
    Computer Science student at the University of Florida.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jacobejenkins.com" # the base hostname & protocol for your site
twitter_username: j4cobj
github_username:  jacobj

# Build settings
markdown: kramdown
